/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;

namespace ThriftCommon.Calculator
{
  public class Constants
  {
    public static int INT32CONSTANT = 9853;
    public static Dictionary<string, string> MAPCONSTANT = new Dictionary<string, string>();
    static Constants()
    {
      MAPCONSTANT["goodnight"] = "moon";
      MAPCONSTANT["hello"] = "world";
    }
  }
}
